### ISSUE TITLE
Request for Code of discrete EDI processing

### ISSUE THREAD

**Issue by yuchenweng-private** [iCVTEAM/E2NeRF#3]
Hi, thanks to your great work, can you provide the code that is used to preprocessing of blurry images by using EDI?
I wanna know how clear is the input images.
Thank you !!!!!

**Comment by 171164558** [comment]
Thanks. I have updated the EDI code in the repository.

**Comment by trishagithubreddypalli** [comment]
Hello @171164558!

Thank you for open sourcing this good work..

When we use EDI model to deblur, images are not getting deblurred properly, they are noisy, hence colmap is not working with these as a input.

Do you suggest to solve this issue?

If it is possible, can you please open source dataset as well once you deblur.

Thank you

**Comment by 171164558** [comment]
Thanks.

The deblurred images of EDI model are indeed noisy. You can attempt to adjust the threshold of the EDI model (0.3 in lines 13 and 23 of EDI.py) to generate better results. Also, you can attempt to run the colmap again with the deblurred images because it may sometimes fail, even with the same input.

If this still can not work, please feel free to contact me (qi_yunshan@buaa.edu.cn).
