### ISSUE TITLE
Request for the dataset after EDI model

### ISSUE THREAD

**Issue by trishagithubreddypalli** [iCVTEAM/E2NeRF#4]
Hello @171164558!

Thank you for open sourcing this good work..

When we use EDI model to deblur, images are not getting deblurred properly, they are noisy, hence colmap is not working with these as a input.

Do you suggest to solve this issue?

If it is possible, can you please open source dataset as well once you deblur.

Thank you

**Comment by 171164558** [comment]
Thanks.

The deblurred images of EDI model are indeed noisy. You can attempt to adjust the threshold of the EDI model (0.3 in lines 13 and 23 of EDI.py) to generate better results. Also, you can attempt to run the colmap again with the deblurred images because it may sometimes fail, even with the same input.

If this still can not work, please feel free to contact me ([qi_yunshan@buaa.edu.cn](mailto:qi_yunshan@buaa.edu.cn)).
